@startuml
'https://plantuml.com/class-diagram


Employee <|-- BaseEmployee
Employee <|-- CommissionEmployee
Employee <|-- HourlyEmployee
Employee <|-- SalariedEmployee

class Employee {
-FirstName: String
-LastName: String
-SSNumber: String

+Employee(FirstName: String, LastName: String, SSNumber: String)
+setFirstName(FirstName: String): void
+setLastName(LastName: String): void
+setSSNumber(SSNumber: String): void
+getFirstName(): String
+getLastName(): String
+getSSNumber(): String
}

class BaseEmployee{
-BaseSalary: String

+BaseEmployee(FirstName: String,LastName: String, SSNumber: String, BaseSalary: String)
+setBaseSalary(BaseSalary: String): void
+getBaseSalary(): String
+Print(): void
}

class CommissionEmployee{
-CommissionRate: String
-GrossSales: String

+CommissionEmployee(FirstName: String,LastName: String, SSNumber: String, CommissionRate: String, GrossSales: String)
+setCommissionRate(CommissionRate: String): void
+setGrossSales(GrossSales: String): void
+getCommissionRate(): String
+String getGrossSales(): String
+Print(): void
}

class HourlyEmployee{
-Wage: String
-NumberHoursWorked: String

+HourlyEmployee(FirstName: String, LastName: String, SSNumber: String, Wage: String, NumberHoursWorked: String)
+setWage(Wage: String): void
+setNumberHoursWorked(NumberHoursWorked: String): void
+getWage(): String
+getNumberHoursWorked(): String
+Print(): void
}

class SalariedEmployee{
-WeeklySalary: String

+SalariedEmployee(FirstName: String,LastName: String, SSNumber: String, WeeklySalary: String)
+setWeeklySalary(WeeklySalary: String): void
+getWeeklySalary(): String
+Print(): void
}

@enduml