@startuml
'https://plantuml.com/class-diagram


Folder "1" *-- "0..*" File
Folder "1" *-- "0..*" Folder


class Folder {
-FolderName: String

+Folder(FolderName: String)
+getFolderName(): String
+setFolderName(FolderName: String): void
+AddNewFolder(NewFolderName: String): void
+AddNewFolder(NewFolder: Folder): void
+AddNewFile(NewFileName: String): void
+Print(): void
+Delete(Selection: Folder): void
}

class File{
-FileName: String

+File(FileName: String)
+setFileName(FileName: String): void
+getFileName(): String
+PrintFileName(): void
}

@enduml