@startuml
'https://plantuml.com/class-diagram

Ship <|-- CruiseShip
Ship <|-- CargoShip

class Ship {
-ShipName: String
-YearBuilt : String

+Ship(ShipName: String, YearBuilt: String)
+getShipName(): String
+getYearBuilt(): String
+setShipName(ShipName: String): void
+setYearBuilt(YearBuilt: String): void
+PrintShip(): void
}

class CruiseShip{
-MaxNumberOfPassengers: int

+CruiseShip(ShipName: String, YearBuilt: String, MaxNumberOfPassengers: int)
+setMaxNumberOfPassengers(MaxNumberOfPassengers: int): void
+getMaxNumberOfPassengers(): int
+PrintShip(): void
}

class CargoShip{
-Tonnage: int

+CargoShip(ShipName: String, YearBuilt: String, Tonnage: int)
+setTonnage(Tonnage: int): void
+getTonnage(): int
+PrintShip(): void
}

@enduml