@startuml
'https://plantuml.com/class-diagram


class Course {
-CourseName: String
-CourseInstructorA: Instructor
-CourseInstructorB: Instructor
-CourseTextbookA: Textbook
-CourseTextbookB: Textbook

+Course(CourseName: String, CourseInstructorA: Instructor, CourseInstructorB: Instructor, CourseTextbookA: Textbook, CourseTextbookB: Textbook)
+getCourseName(): String
+setCourseName(CourseName: String): void
+PrintCourseDetails(): void
}

class Instructor {
-FirstName: String
-LastName: String
-OfficeNumber: String

+Instructor(FirstName: String, LastName: String, OfficeNumber: String)
+getFirstName(): String
+getLastName(): String
+getOfficeNumber(): String
+setFirstName(FirstName: String): void
+setLastName(LastName: String): void
+setOfficeNumber(OfficeNumber: String): void
}

class Textbook {
-Title: String
-Author: String
-Publisher: String

+Textbook(Title: String, AuthorName: String, Publisher: String)
+getTitle(): String
+getAuthorName(): String
+getPublisher(): String
+setTitle(Title: String): void
+setAuthorName(AuthorName: String): void
+setPublisher(Publisher: String): void
}

Course "1..*" o-- "2" Instructor
Course "0..*" o-- "2" Textbook

@enduml